package klikbca

import (
	"crypto/md5"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
	"github.com/gocolly/colly"
)

type settlementDetail struct {
	// ID is generated by a formula of hash(date+type+description+amount)
	ID string `json:"id"`
	// Date has a format of DD/MM
	Date string `json:"date"`
	// Type is the bookkeeping type of the transaction. It is either CR or DB
	// which stands for CREDIT or DEBIT
	Type        string `json:"type"`
	Description string `json:"description"`
	Amount      string `json:"amount"`
}

func generateID(date, bookKeepType, outerHTML string) string {
	return fmt.Sprintf("%x", md5.Sum([]byte(date+bookKeepType+outerHTML)))
}

func processSettlement(date, bookKeepType, outerHTML string) []settlementDetail {

	settlement := []settlementDetail{}

	for _, data := range strings.Split(outerHTML, "\n") {
		// First we sanitize the data by removing <td>
		data = strings.Replace(data, "<td>", "", -1)
		// Second we sanitize the data by remomving </td>
		data = strings.Replace(data, "</td>", "", -1)
		// Then we split the data with <br/> so we can separate the amont data
		splittedData := strings.Split(data, "<br/>")
		// We can rejoin the splitted data to build a description of the transaction
		// Also not forgetting to remove the last item of the array, because it contains the amount
		description := strings.Join(splittedData[0:len(splittedData)-1], " ")
		// The amount should always be in the last item of the array
		amount := splittedData[len(splittedData)-1]

		settlement = append(settlement, settlementDetail{
			ID:          generateID(date, bookKeepType, data),
			Date:        date,
			Type:        bookKeepType,
			Description: description,
			Amount:      amount,
		})
	}

	return settlement
}

func (klikBca klikBca) GetTodaySettlement() ([]settlementDetail, error) {

	var err error
	settlement := []settlementDetail{}

	klikBca.colly.OnHTML(dailySettlementSelector, func(e *colly.HTMLElement) {

		if strings.Contains(string(e.Response.Body), "TIDAK ADA TRANSAKSI") {
			// This should return an empty array
			return
		}

		date := e.DOM.Find("td:first-child").Text()
		bookKeepType := e.DOM.Find("td:last-child").Text()

		// If date is PEND we do not want to append it on the response
		if date == "PEND" {
			return
		}

		// Need to retain the HTML codes, because the data is separated by <br>s which we can extract easily.
		// If we only extract by Text(), we cannot extract the data
		outerHTML, outerHTLMParseErr := goquery.OuterHtml(e.DOM.Find("td:not([valign])"))
		if err != nil {
			err = outerHTLMParseErr
			return
		}

		// Start processing data
		settlement = append(settlement, processSettlement(date, bookKeepType, outerHTML)...)
	})

	// Login
	form := url.Values{}
	form.Add("value(user_id)", klikBca.username)
	form.Add("value(pswd)", klikBca.password)
	form.Add("value(Submit)", "LOGIN")
	form.Add("value(actions)", "login")
	form.Add("value(user_ip)", klikBca.ipAddress)
	form.Add("user_ip", klikBca.ipAddress)
	form.Add("value(mobile)", "true")
	form.Add("mobile", "true")

	err = klikBca.colly.Request(
		"POST",
		"https://m.klikbca.com/authentication.do",
		strings.NewReader(form.Encode()),
		nil,
		http.Header{
			"Content-Type": []string{"application/x-www-form-urlencoded"},
		},
	)
	if err != nil {
		return nil, err
	}

	// Go to account information page. This is the place where you can go to the "Balance", "Settlement" etc page
	err = klikBca.colly.Request(
		"POST",
		"https://m.klikbca.com/accountstmt.do?value(actions)=menu",
		nil,
		nil,
		http.Header{},
	)
	if err != nil {
		return nil, err
	}

	// Go to account statement page
	err = klikBca.colly.Request(
		"POST",
		"https://m.klikbca.com/accountstmt.do?value(actions)=acct_stmt",
		nil,
		nil,
		http.Header{},
	)
	if err != nil {
		return nil, err
	}

	// Get formatted time
	now := time.Now()
	date := now.Format("02")
	month := now.Format("01")
	year := now.Format("2006")

	form = url.Values{}
	form.Add("value(D1)", "0")
	form.Add("value(r1)", "1")
	form.Add("value(startDt)", date)
	form.Add("value(startMt)", month)
	form.Add("value(startYr)", year)
	form.Add("value(endDt)", date)
	form.Add("value(endMt)", month)
	form.Add("value(endYr)", year)
	form.Add("value(fDt)", "")
	form.Add("value(tDt)", "")
	form.Add("value(submit1)", "View Account Statement")

	// Get the settlement for today
	err = klikBca.colly.Request(
		"POST",
		"https://m.klikbca.com/accountstmt.do?value(actions)=acctstmtview",
		strings.NewReader(form.Encode()),
		nil,
		http.Header{},
	)
	if err != nil {
		return nil, err
	}

	klikBca.colly.Visit("https://m.klikbca.com/authentication.do")

	return settlement, err
}
